### PR TITLE
opt_parse: avoid potential heap-buffer-overflow when parsing non-ASCII characters (affect cct and gie)

### LINKED ISSUE #4528: Heap Overflow in optargpm.h
Hi, we have found a heap buffer overflow and would like to report this issue.
Could you confirm if this qualifies as a valid bug? I am happy to provide any additional information needed.

## Summary

A heap overflow occurs due to index access using signed char.

### Tested Environment
- Operating System: Ubuntu 24.04 LTS
- Architecture: x86_64
- Compiler: clang with Address Sanitizer (clang version: 18.1.3)

### Reproduction steps
There are problems in both cases: when the command line argument has one `-` and when it has two `-`.
The case with one `-` is referred to as case1, and the case with two `-` is referred to as case2.

```bash
# Build
export AFL_USE_ASAN=1
export CC=afl-clang-fast
export CXX=afl-clang-fast++

export CFLAGS="-fsanitize=address -g -O1"
export CXXFLAGS="-fsanitize=address -g -O1"
export LDFLAGS="-fsanitize=address"

mkdir -p build
cd build
cmake ..
make
```

```bash
#case 1: single hyphen case
# note: 'ｖ' is -xefbd96 of utf8.
./bin/gie -ｖ

#case2 : double hyphen case
#note:  Only one character can be reproduced after the double hyphen.
./bin/gie $(perl -e 'print join "", map { chr } (45, 45, 243)' )
```

#### case1
```

=================================================================
==36984==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x51d000000a58 at pc 0x558b5ed46112 bp 0x7ffe563db830 sp 0x7ffe563db828
READ of size 8 at 0x51d000000a58 thread T0
    #0 0x558b5ed46111 in opt_parse(int, char**, char const*, char const*, char const**, char const**) /tmp/PROJ/src/apps/optargpm.h:610:28
    #1 0x558b5ed4668e in main /tmp/PROJ/src/apps/gie.cpp:282:9
    #2 0x7d546942a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #3 0x7d546942a28a in __libc_start_main csu/../csu/libc-start.c:360:3
    #4 0x558b5ec645c4 in _start (/tmp/PROJ/build/bin/gie+0x305c4) (BuildId: ea89b7d13fdc4caf822bca10b5081bc67843b1fe)

0x51d000000a58 is located 40 bytes before 2176-byte region [0x51d000000a80,0x51d000001300)
allocated by thread T0 here:
    #0 0x558b5ed02cbc in calloc (/tmp/PROJ/build/bin/gie+0xcecbc) (BuildId: ea89b7d13fdc4caf822bca10b5081bc67843b1fe)
    #1 0x558b5ed43d7e in opt_parse(int, char**, char const*, char const*, char const**, char const**) /tmp/PROJ/src/apps/optargpm.h:441:20
    #2 0x558b5ed4668e in main /tmp/PROJ/src/apps/gie.cpp:282:9
    #3 0x7d546942a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #4 0x7d546942a28a in __libc_start_main csu/../csu/libc-start.c:360:3
    #5 0x558b5ec645c4 in _start (/tmp/PROJ/build/bin/gie+0x305c4) (BuildId: ea89b7d13fdc4caf822bca10b5081bc67843b1fe)

SUMMARY: AddressSanitizer: heap-buffer-overflow /tmp/PROJ/src/apps/optargpm.h:610:28 in opt_parse(int, char**, char const*, char const*, char const**, char const**)
Shadow bytes around the buggy address:
  0x51d000000780: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x51d000000800: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x51d000000880: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x51d000000900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x51d000000980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x51d000000a00: fa fa fa fa fa fa fa fa fa fa fa[fa]fa fa fa fa
  0x51d000000a80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51d000000b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51d000000b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51d000000c00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51d000000c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==36984==ABORTING
```

#### case2
```
=================================================================
==36899==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x51d000000a78 at pc 0x60f941fb5ad1 bp 0x7ffc415a9070 sp 0x7ffc415a9068
READ of size 8 at 0x51d000000a78 thread T0
    #0 0x60f941fb5ad0 in opt_ordinal(OPTARGS*, char const*) /tmp/PROJ/src/apps/optargpm.h:345:24
    #1 0x60f941fb6f1c in opt_parse(int, char**, char const*, char const*, char const**, char const**) /tmp/PROJ/src/apps/optargpm.h:561:21
    #2 0x60f941fb868e in main /tmp/PROJ/src/apps/gie.cpp:282:9
    #3 0x79405942a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #4 0x79405942a28a in __libc_start_main csu/../csu/libc-start.c:360:3
    #5 0x60f941ed65c4 in _start (/tmp/PROJ/build/bin/gie+0x305c4) (BuildId: ea89b7d13fdc4caf822bca10b5081bc67843b1fe)

0x51d000000a78 is located 8 bytes before 2176-byte region [0x51d000000a80,0x51d000001300)
allocated by thread T0 here:
    #0 0x60f941f74cbc in calloc (/tmp/PROJ/build/bin/gie+0xcecbc) (BuildId: ea89b7d13fdc4caf822bca10b5081bc67843b1fe)
    #1 0x60f941fb5d7e in opt_parse(int, char**, char const*, char const*, char const**, char const**) /tmp/PROJ/src/apps/optargpm.h:441:20
    #2 0x60f941fb868e in main /tmp/PROJ/src/apps/gie.cpp:282:9
    #3 0x79405942a1c9 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #4 0x79405942a28a in __libc_start_main csu/../csu/libc-start.c:360:3
    #5 0x60f941ed65c4 in _start (/tmp/PROJ/build/bin/gie+0x305c4) (BuildId: ea89b7d13fdc4caf822bca10b5081bc67843b1fe)

SUMMARY: AddressSanitizer: heap-buffer-overflow /tmp/PROJ/src/apps/optargpm.h:345:24 in opt_ordinal(OPTARGS*, char const*)
Shadow bytes around the buggy address:
  0x51d000000780: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x51d000000800: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x51d000000880: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x51d000000900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x51d000000980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x51d000000a00: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa[fa]
  0x51d000000a80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51d000000b00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51d000000b80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51d000000c00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x51d000000c80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==36899==ABORTING
```

#### case1 
[[src/apps/optargpm.h:537](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L537)](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L537)
Here, a character is extracted from the command line argument and stored in variable `c` as a signed char.

[[src/apps/optargpm.h:610](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L610)](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L610)
Here, `c` is used as an index to access an array of length 256 (o->optarg).
If `c` is negative, it will access other areas of `o` or unallocated memory regions.

Related code:
[[src/apps/optargpm.h:227](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L227)](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L227)
optarg is an array of char arrays with 256 elements.

[[src/apps/optargpm.h:441](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L441)](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L441)
The memory area for the OPTARGS structure containing optarg is allocated here.

#### case2
[[src/apps/optargpm.h:345](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L345)](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L345)
In this opt_ordinal function, option[0], which is part of the argv value, is treated as an int and used to access an array of length 256 (o->optarg).
If option[0] is negative, it will access other areas of `o` or unallocated memory regions.

Related code:
[[src/apps/optargpm.h:561](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L561)](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L561)
When there is an argv[i] that starts with two hyphens, the opt_ordinal function is called.
It takes a pointer to OPTARGS and a pointer to an array of length 2 consisting of argv[i][2] and a null character as arguments.

[[src/apps/optargpm.h:538](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L538)](https://github.com/OSGeo/PROJ/blob/db3a7e79a6faff76e8066d35404474234cefd256/src/apps/optargpm.h#L538)
Here, an array of length 2 consisting of argv[i][2] and a null character is created to pass to the opt_ordinal function.

## Proposed Fix
```diff
diff --git a/src/apps/optargpm.h b/src/apps/optargpm.h
index a3dcd19..a669afb 100644
--- a/src/apps/optargpm.h
+++ b/src/apps/optargpm.h
@@ -342,7 +342,7 @@ static int opt_ordinal(OPTARGS *opt, const char *option) {
     /* An ordinary -o style short option */
     if (strlen(option) == 1) {
         /* Undefined option? */
-        if (nullptr == opt->optarg[(int)option[0]])
+        if (nullptr == opt->optarg[(unsigned char)option[0]])
             return 0;
         return (int)option[0];
     }
@@ -534,7 +534,7 @@ OPTARGS *opt_parse(int argc, char **argv, const char *flags, const char *keys,
         o->margc++;
 
         for (j = 1; j < arg_group_size; j++) {
-            int c = argv[i][j];
+            unsigned char c = argv[i][j];
             char cstring[2], *crepr = cstring;
             cstring[0] = (char)c;
             cstring[1] = 0;
@@ -630,7 +630,7 @@ OPTARGS *opt_parse(int argc, char **argv, const char *flags, const char *keys,
                     free(o);
                     return nullptr;
                 }
-                o->optarg[(int)c] = argv[i + 1];
+                o->optarg[c] = argv[i + 1];
                 i++;
                 break;
             }
```

### PR DESCRIPTION
**Pull request by rouault**
and cct and gie: return error code 1 when argument parsing fails

Fixes #4528

### CODE REVIEW

File: src/apps/optargpm.h [hunk 1]
```diff
@@ -224,8 +227,8 @@ struct OPTARGS {
     const char *progname; /* argv[0], stripped from /path/to, if present */
     char flaglevel[21];   /* if flag -f is specified n times, its optarg pointer
                              is   set to flaglevel + n */
-    char *optarg[256]; /* optarg[(int) 'f'] holds a pointer to the argument of
-                          option "-f" */
+    char *optarg[OPTARG_SIZE]; /* optarg[(usigned char) 'f'] holds a pointer to
```
Comment (QuLogic) [inline src/apps/optargpm.h]:
```suggestion
    char *optarg[OPTARG_SIZE]; /* optarg[(unsigned char) 'f'] holds a pointer to
```

File: src/apps/optargpm.h [hunk 2]
```diff
@@ -224,8 +227,8 @@ struct OPTARGS {
...
+                          the argument of option "-f" */
```
Comment (QuLogic) [inline src/apps/optargpm.h]: Wrapped line seems misaligned, unless GitHub is not rendering tabs correctly.

File: src/apps/optargpm.h (hunk 1 above)
Comment (rouault) [reply src/apps/optargpm.h]: fixed
